services:
  frontend:
    build: ./frontend
    container_name: angular_frontend
    ports:
      - '4200:80'
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: express_backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: booksdb
      DB_PORT: 5432

  db:
    image: postgres:17.4
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booksdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
